Index of 50th element
---------

Consider an (8, 8) shape NumPy array. What is the index (x,y) of the 50th element?

Note: For counting the elements go row-wise. For example, in the array,

    [[1, 5, 9],

    [3, 0, 2]]

the 5th element would be '0'.


    (6, 1)

    You can create an 8 x 8 array using np.array(range(1, 8*8+1)),
    reshape it to an (8 x 8) array and then, check the position of 50. 

    Be clear that the indexing starts from 0; 
    hence, the 7th row will have the index 6.

    Alternatively, you can also use np.unravel_index(49, (8,8)) on the created array.


- (6, 2)


- (7, 1)


- (7, 2)

In [2]:
import numpy as np
np.unravel_index(49, (8,8))

(6, 1)

Slicing Arrays
-----

Which of the following would extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?


- a[ :3, :5 ]


- a[ :3 , 5: ] 


- a[ :3 , :-5 ]


    a[ :3 , -5: ]

    This would extract the first 3 rows and the last five columns. 
    The index after the comma, i.e., the index representing the columns specifies "-5:". 
    This will extract all the columns starting from the 5th last column. 

So Many Functions
------------

What will the output of np.arange(1,16,2).reshape(4, 2) be?

------------

`Feedback:`

np.arange(1,16,2) returns the following array:

    [ 1,  3,  5,  7,  9, 11, 13, 15]


The reshape(4, 2) function then reshapes it into a (4 x 2) matrix. Hence, the matrix now becomes -

    [[ 1,  3],
      [ 5,  7],
      [ 9, 11],
      [13, 15]]

In [4]:
arr = np.arange(1,16,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [5]:
arr.reshape(4, 2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

Print "+"
---------

Description

Given a single positive odd integer 'n' greater than 2, create a NumPy array of size (n x n) with all zeros and ones such that the ones make a shape like '+'. The lines of the plus must be present at the middle row and column.

Hint: 

Start by creating a (n x n) array with all zeroes using the np.zeros() function and then fill in the ones at the appropriate indices. Use integer division (//) to access the middle rows and columns

`Examples:`

    Input 1:
    3

    Output 1:

    [[0 1 0]
    [1 1 1]
    [0 1 0]]

    Input 2:
    5

    Output 1:

    [[0 0 1 0 0]
    [0 0 1 0 0]
    [1 1 1 1 1]
    [0 0 1 0 0]
    [0 0 1 0 0]]

Explanation: 

Notice that the 1s in the arrays make a shape like '+'.

In [9]:
import numpy as np

# inp = int(input())
inp = 5

arr = np.zeros((inp, inp), dtype = int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
arr[inp//2] = 1 # middle row
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
for i in range(inp):
  arr[i, inp//2] = 1 # middle column for each row

arr

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])

In [13]:
# Ans.

# Read the input
n = int(input())

# Import the NumPy package
import numpy as np 

# Create an (n x n) array with all zeros
z = np.zeros((n, n), dtype = int)

# Make the middle row and middle column all 1s
z[n//2, :] = 1
z[: , n//2] = 1
    
# Print the final value of z    
print(z)

3
[[0 1 0]
 [1 1 1]
 [0 1 0]]
