## Practice Exercise 1

You are provided with `2 lists` that contain the data of an ecommerce website. 

The `first list` contains the data for the `number of items sold` for a particular product,

and the `second list` contains the `price of the product sold`. 

As a part of this exercise, solve the questions that are provided below.

In [1]:
number = [8, 9, 9, 1, 6, 9, 5, 7, 3, 9, 7, 3, 4, 8, 3, 5, 8, 4, 8, 7, 5, 7, 3, 6, 1, 2, 7, 4, 7, 7, 8, 4, 3, 4, 2, 2, 2, 7, 3, 5, 6, 1, 1, 3, 2, 1, 1, 7, 7, 1, 4, 4, 5, 6, 1, 2, 7, 4, 5, 8, 1, 4, 8, 6, 2, 4, 3, 7, 3, 6, 2, 3, 3, 3, 2, 4, 6, 8, 9, 3, 9, 3, 1, 8, 6, 6, 3, 3, 9, 4, 6, 4, 9, 6, 7, 1, 2, 8, 7, 8, 1, 4]
price = [195, 225, 150, 150, 90, 60, 75, 255, 270, 225, 135, 195, 30, 15, 210, 105, 15, 30, 180, 60, 165, 60, 45, 225, 180, 90, 30, 210, 150, 15, 270, 60, 210, 180, 60, 225, 150, 150, 120, 195, 75, 240, 60, 45, 30, 180, 240, 285, 135, 165, 180, 240, 60, 105, 165, 240, 120, 45, 120, 165, 285, 225, 90, 105, 225, 45, 45, 45, 75, 180, 90, 240, 30, 30, 60, 135, 180, 15, 255, 180, 270, 135, 105, 135, 210, 180, 135, 195, 225, 75, 225, 15, 240, 60, 15, 180, 255, 90, 15, 150, 230, 150]

In [2]:
import numpy as np
number = np.array(number)
price = np.array(price)

#### How many different products are sold by the company in total?

-  99
-  100
-  101
-  102


In [3]:
# Type your code here
len(number)

102

In [4]:
# Ans.
number.size

102

In [5]:
number.shape

(102,)

#### How many items were sold in total?

-  460
-  490
-  500
-  520


In [6]:
# Type your code here
np.sum(number)

490

In [7]:
# Ans.
number.sum()

490

#### What is the average price of the products sold by the ecommerce company?

-  139
-  151
-  142
-  128

In [8]:
# Type your code here
price.sum() // price.size

139

In [9]:
# Ans.
price.mean()

139.01960784313727

#### What is the price of the costliest item sold?

-  225
-  310
-  280
-  285

In [10]:
# Type your code here
price.max()

285

In [11]:
# Ans.
np.max(price)

285

#### What is the total revenue of the company? [Revenue = Price\*Quantity]

-  67100
-  53900
-  45300
-  71200

In [12]:
# Type your code here
rev = price * number
rev

array([1560, 2025, 1350,  150,  540,  540,  375, 1785,  810, 2025,  945,
        585,  120,  120,  630,  525,  120,  120, 1440,  420,  825,  420,
        135, 1350,  180,  180,  210,  840, 1050,  105, 2160,  240,  630,
        720,  120,  450,  300, 1050,  360,  975,  450,  240,   60,  135,
         60,  180,  240, 1995,  945,  165,  720,  960,  300,  630,  165,
        480,  840,  180,  600, 1320,  285,  900,  720,  630,  450,  180,
        135,  315,  225, 1080,  180,  720,   90,   90,  120,  540, 1080,
        120, 2295,  540, 2430,  405,  105, 1080, 1260, 1080,  405,  585,
       2025,  300, 1350,   60, 2160,  360,  105,  180,  510,  720,  105,
       1200,  230,  600])

In [13]:
# Ans.
rev.sum()

67100

#### Demand for the 20th product in the list is more than the 50th product. [True/False]
-  True
-  False
-  Can't be calculated

In [14]:
# Type your code here

# display() is same as writing in last 
# line of cell and printing formatted.
# try display() function on DataFrame.

num20th = number[19]
display(num20th)

num50th = number[49]
display(num50th)

num20th > num50th

7

1

True

In [15]:
# Ans.
number[19] > number[49]

True

#### How many products fall under the category of expensive goods? 
An expensive good is that good whose price is more than the average price of the products sold by the company.

-  48
-  50
-  52
-  54

In [16]:
# Type your code here
exp = price > price.mean()
exp

array([ True,  True,  True,  True, False, False, False,  True,  True,
        True, False,  True, False, False,  True, False, False, False,
        True, False,  True, False, False,  True,  True, False, False,
        True,  True, False,  True, False,  True,  True, False,  True,
        True,  True, False,  True, False,  True, False, False, False,
        True,  True,  True, False,  True,  True,  True, False, False,
        True,  True, False, False, False,  True,  True,  True, False,
       False,  True, False, False, False, False,  True, False,  True,
       False, False, False, False,  True, False,  True,  True,  True,
       False, False, False,  True,  True, False,  True,  True, False,
        True, False,  True, False, False,  True,  True, False, False,
        True,  True,  True])

In [17]:
exprice = price[exp]
exprice

array([195, 225, 150, 150, 255, 270, 225, 195, 210, 180, 165, 225, 180,
       210, 150, 270, 210, 180, 225, 150, 150, 195, 240, 180, 240, 285,
       165, 180, 240, 165, 240, 165, 285, 225, 225, 180, 240, 180, 255,
       180, 270, 210, 180, 195, 225, 225, 240, 180, 255, 150, 230, 150])

In [18]:
exprice.size

52

In [19]:
# Ans. (always try oneliner answers)
price[price > price.mean()].size 

52