Creating an Array
----------

Select the correct option to create a 1-d array using the following elements (1.0, 2, 3.5, 0.2, True). 

(Note that ‘True’ must be provided as a Boolean value, not as a string.)


- np.array(1.0, 2, 3.5, 0.2, True)

- np.array( [1.0, 2, 3.5, 0.2, "True"] )


    - np.array( [1.0, 2, 3.5, 0.2, True] )
    
    This is the correct answer. 
    You have to provide the elements in the form of a list or a tuple to form an array. 
    Also, a Boolean value is defined without the apostrophes.


- np.array[1.0, 2, 3.5, 0.2, True]

In [ ]:
import numpy as np

lst = [1.0, 2, 3.5, 0.2, True]
arr = np.array( lst )

arr

array([1. , 2. , 3.5, 0.2, 1. ])

NumPy Array
----------

What is the default data type of each element in the array created in the previous question?


- String


- Integer


    - Float

    Float can accommodate the integer values; 
    hence, all the values are converted to float. 
    
    Check the output in Jupyter notebook to confirm.


- Boolean

In [ ]:
type(arr[1]), type(arr[-1])

(numpy.float64, numpy.float64)

Creating an array
-----------

Is it possible to create an array from a tuple?


    - Yes

    Yes, NumPy arrays can be created using a tuple. 
    Any sequence that has an array-like structure can 
    be passed to the np.array function.


- No

In [ ]:
tup = (1.0, 2, 3.5, 0.2, True)
np.array(tup)

array([1. , 2. , 3.5, 0.2, 1. ])

Indexing Array
----------

Given an array:

    array_1 = [1,2,3,5,4,6,7,8,5,3,2]

What will be the output of the code provided below?

    print(array_1[:3])
 


- [1, 2, 3, 5]


    - [1, 2, 3]

    The function only gives the first three entries, 
    and this answer follows that.


- [2, 3, 5]

In [ ]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[:3])

[1, 2, 3]


Indexing Array
----------

Given an array:

    array_1 = [1,2,3,5,4,6,7,8,5,3,2]

What will be the output of the code provided below?

    print(array_1[2:-3])
 

- [2 3 5 4 6 7 8]


    - [3 5 4 6 7 8]
    
    The desired values start from the third entry (included) 
    in the array until the third last entry (excluded).


- [3 5 4 6 7 8 5]
 

In [ ]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[2:-3])

[3, 5, 4, 6, 7, 8]


Indexing Array
----------

Given an array:

    array_1 = [1,2,3,5,4,6,7,8,5,3,2]

What will be the output of the code provided below?

(Hint: The syntax is [starting value : end value : step value])

    print(array_1[ : : -2])
 


- [2, 5, 6, 8, 3]
 

- [1, 3, 4, 7, 5, 2]
 


    - [2, 5, 7, 4, 3, 1]
    
    The syntax is [starting value : end value : skip value]. 
    Here, since the skip value is negative, 
    it means that we will start from the opposite direction 
    take every second value in the array

In [ ]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[ : : -2])

[2, 5, 7, 4, 3, 1]


Indexing Array
----------

How would you extract all the elements with an odd index in a given array?

(Hint: Odd index refers to the position of the element, not the actual value)


- array[1:1]

- array[: : 2]


    - array[1: : 2]

    The syntax here will give all the elements at odd indices.


- array[1:2]

In [ ]:
array = [0,1,2,3,4,5,6,7,8,9]
array[1: : 2]

[1, 3, 5, 7, 9]

Extracting Elements from Array
----------

Description

From a given array, extract all the elements which are greater than 'm' and less than 'n'. Note: 'm' and 'n' are integer values provided as input.



Input format:

A list of integers on line one

Integer 'm' on line two

Integer 'n' on line three



Output format:

1-D array containing integers greater than 'm' and smaller than 'n'.





Sample input:

[ 1, 5, 9, 12, 15, 7, 12, 9 ] (array)

6 (m)

12 (n)



Sample output:

[ 9 7 9 ]





Sample input:

[ 1, 5, 9, 12, 15, 7, 12, 9 ]

12

6



Sample output:

[ ]

In [ ]:
lst = [ 1, 5, 9, 12, 15, 7, 12, 9 ]
lst

[1, 5, 9, 12, 15, 7, 12, 9]

In [ ]:
m = 6
n = 12
m, n

(6, 12)

In [ ]:
import numpy as np
lstnp = np.array(lst)
lstnp

array([ 1,  5,  9, 12, 15,  7, 12,  9])

In [ ]:
print(lstnp[(lstnp > m) & (lstnp < n)])

[9 7 9]


In [ ]:
# Ans.
import ast 

input_list=ast.literal_eval(input())
m=int(input())
n=int(input())

import numpy as np
array_1 = np.array(input_list)
final_array = array_1[(array_1 > m) & (array_1 < n)]

print(final_array)

[1, 5, 9, 12, 15, 7, 12, 9]
6
12
[9 7 9]


# Axis

In NumPy, the dimension is called axis. 

In NumPy terminology, for 2-D arrays:

    axis = 0 - refers to the rows
    axis = 1 - refers to the columns

![ss](https://cdn.upgrad.com/UpGrad/temp/955dae3c-d41c-41db-8ef1-4c38d50f96ef/2_d_array.png)

Slicing Arrays
-------

Which of the following would extract all the rows of the first 3 columns in a 2D array?


- array_name[ : , :2]

- array_name[( : , :2)]


    - array_name[ : , :3]
    array_name[:,:3] extracts all the rows of the first 3 columns. 
    
    Note that even though the first 3 columns have the indices 0, 1, and 2, respectively, 

    we need to mention array_name[:,:3] instead of array_name[:,:2] 
    since the last column index mentioned is not included, 

    i.e., array_name[:,:2] will give you just the first two columns, 
    i.e., 0 and 1.

- array_name[( : , :3)]

Border Rows and Columns
-----------------

Description

Extract all the border rows and columns from a 2-D array.

Format:
Input: A 2-D Python list
Output: Four NumPy arrays - First column of the input array, first row of the input array, last column of the input array, last row of the input array respectively.

`Example:`

    Input 1:

    [[11 12 13 14]
    [21 22 23 24]
    [31 32 33 34]]
    
    Output 1:

    [11 21 31]
    [11 12 13 14]
    [14 24 34]
    [31 32 33 34]

In [ ]:
# Read the input list
import ast, sys
import numpy as np

# input_str = sys.stdin.readlines()
input_str = input()
input_list = ast.literal_eval(input_str)

# Convert the input list to a NumPy array
array_2d = np.array(input_list)

# Extract the first column, first row, last column and last row respectively using
# appropriate indexing

col_first = array_2d[ : , 0]
row_first = array_2d[ 0 , :]
col_last = array_2d[ : , -1]
row_last = array_2d[ -1 , :]

print(col_first)
print(row_first)
print(col_last)
print(row_last)


# INPUT:
# [[11, 12, 13, 14],
#  [21, 22, 23, 24],
#  [31, 32, 33, 34]]


[[11, 12, 13, 14],  [21, 22, 23, 24],  [31, 32, 33, 34]]
[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


In [ ]:
# Ans.

# Read the input list
import ast,sys
input_str = sys.stdin.read()
input_list = ast.literal_eval(input_str)

import numpy as np
# Convert the input list to a NumPy array
array_2d = np.array(input_list)

# Extract the first column, first row, last column and last row respectively using
# appropriate indexing

col_first = array_2d[ : ,  0]
row_first = array_2d[ 0 ,  :]
col_last  = array_2d[ : , -1]
row_last  = array_2d[-1 ,  :]

print(col_first)
print(row_first)
print(col_last)
print(row_last)

### The following ways are commonly used when you know the size of the array beforehand:

- np.ones(): It is used to create an array of 1s.
- np.zeros(): It is used to create an array of 0s.
- np.random.randint(): It is used to create a random array of integers within a particular range.
- np.random.random(): It is used to create an array of random numbers.
- np.arange(): It is used to create an array with increments of fixed step size.
- np.linspace(): It is used to create an array of fixed length.

-----------------

The iPython file attached here has been used in the demonstrations in this segment.

[Creating Numpy Array](https://colab.research.google.com/drive/1gd-h-YFCZT5WjjXK_wzEd_aMrzmCvyy4?authuser=1#scrollTo=rkCVJapEPXZ3)

Array 'arange' Function
------

Description

Create an array of first 10 multiples of 5 using the 'arange' function.

    np.arange(start=1, stop=10, step=3)

In [ ]:
import numpy as np

array_multipleof5 = np.arange(5, 51, 5)

print(array_multipleof5)

[ 5 10 15 20 25 30 35 40 45 50]


Create border array
-----

Description

Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.

Note: 

Make sure the array is of type int.

`Example:`

    Input 1:
    4

    Output 1:

    [[1 1 1 1]
    [1 0 0 1]
    [1 0 0 1]
    [1 1 1 1]]

--------------

    Input 2:
    2

    Output 2:

    [[1 1] 
    [1 1]] 


In [ ]:
# Ans.

# Read the variable from STDIN
n = int(input())
# n = 4

import numpy as np

# Create an 'n*n' array of all ones

# Fill the array with zeroes from second index (i.e. index 1) to second last index.
# Do this for both row indices and column indices

# Print the array created
arr = np.zeros((n, n), dtype = int)
arr[:, 0] = arr[0, :] = arr[:, -1] = arr[-1, :] = 1
arr

4


array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

Index of the 100th Element
------------

Consider an (11,12) shape array. 
What is the index (x,y) of the 100th element? 

Note: 

For counting the elements, go row-wise. 

For example, in the array:

    [[1, 5, 9],
    [3, 0, 2]]

the 5th element would be '0'.


    (8, 3)

    You can create an 11 x 12 array using np.array(range(1, 11*12+1)). 
    You can reshape it to an (11 x 12) array and then check the position of 100. 
    Be clear that the indexing starts from 0; hence, the 9th row will have the index 8.

    Alternatively, you can also use np.unravel_index(99, (11,12)) on the created array.


- (8, 4)


- (9, 3)


- (9, 4)

In [ ]:
arr = np.array(range(1, 11*12 +1))
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132])

In [ ]:
arr = arr.reshape(11, 12)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36],
       [ 37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48],
       [ 49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132]])

In [ ]:
x = 0
for i in arr:
  y = 0
  for j in i:
    if j == 100:
      print((x, y))
      break
    y += 1
  x += 1

(8, 3)


In [ ]:
# Ans.
np.unravel_index(99, (11, 12))

(8, 3)

Reshaping an Array
----

Suppose you have an array 'p':

    [[1, 5],
    [3, 7],
    [4, 9]]

What will be the output of the following code?

    np.reshape(p, -1)

------------

    1-d array

    reshape() function returns a 1-D array when you specify the shape as -1.


- 2-d array

In [ ]:
p = [
  [1, 5],
  [3, 7],
  [4, 9],
]

pnp = np.array(p)
display(pnp)
pnp.shape

array([[1, 5],
       [3, 7],
       [4, 9]])

(3, 2)

In [ ]:
np.reshape(p, -1)

array([1, 5, 3, 7, 4, 9])

Reshaping an Array
----------

Consider the array provided below: 

    [[1, 2, 3, 4, 5]
    [6, 7, 8, 9, 10]
    [11, 12, 13, 14, 15]
    [16, 17, 18, 19, 20]]

Now, you are expected to generate the following array out of it:

    [[1, 3]
    [5, 7]
    [9, 11]
    [13, 15]
    [17, 19]]

Which code will give you the correct output?

(Hint: Also check if one or more options are correct.)

---------

- print(array_1.reshape(5, 4)[array_1%2 != 0])

- print(array_1[array_1%2 != 0])

- print(array_1[array_1%2 == 0].reshape(5, 2))

- print(array_1[array_1%2 != 0].reshape(5, 2))


    print(array_1[array_1%2 != 0].reshape(5, 2))

    This is the correct way to slice odd entries and arrange them in the given order.

In [ ]:
arr = [
  [1, 2, 3, 4, 5],
  [6, 7, 8, 9, 10],
  [11, 12, 13, 14, 15],
  [16, 17, 18, 19, 20],
]

array_1 = np.array(arr)
array_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
# Ans.
array_1[array_1 % 2 != 0].reshape(5, 2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

Reshaping an array
--------------

Suppose you have an array 'p'

    [[1, 5],
    [3, 7],
    [4, 9]]

What will be the output of the following code?

    np.reshape(p, (1, -1))
 
----------

- 1-D Array


    2-D Array

    The dimension of the array is specified by the number of elements you specify in the tuple. 

    Here, the answer is 2-D array.

In [ ]:
p = [
  [1, 5],
  [3, 7],
  [4, 9]
]

arr = np.reshape(p, (1, -1)) # -1 adjust itself accordingly, here 6
arr

array([[1, 5, 3, 7, 4, 9]])

In [ ]:
# Ans.
arr.ndim

2

Stacking arrays
---

Description

Merge the three arrays provided to you to form a one 4x4 array.

[Hint: Check the function np.transpose() in the 'Manipulating Arrays' notebook provided.]

    Input:
    Array 1: 3*3 array

    [[7, 13, 14]
    [18, 10, 17]
    [11, 12, 19]]

    Array 2: 1-D array
    [16, 6, 1]

    Array 3: 1*4 array
    [[5, 8, 4, 3]]

    Output:
    [[7 13 14 5]
    [18 10 17 8]
    [11 12 19 4]
    [16 6 1 3]]

In [ ]:
import ast,sys
import numpy as np

input_list = [
  [
    [7, 13, 14], 
    [18, 10, 17], 
    [11, 12, 19]
  ],

  [16, 6, 1], 

  [
    [5, 8, 4, 3],
  ],
]

list_1 = input_list[0]
list_2 = input_list[1]
list_3 = input_list[2]

mystack = np.vstack((list_1, list_2))
mystack

array([[ 7, 13, 14],
       [18, 10, 17],
       [11, 12, 19],
       [16,  6,  1]])

In [ ]:
list_3 = np.transpose(list_3)
list_3

array([[5],
       [8],
       [4],
       [3]])

In [ ]:
final_array = np.hstack((mystack, list_3))
print(final_array)

[[ 7 13 14  5]
 [18 10 17  8]
 [11 12 19  4]
 [16  6  1  3]]


In [ ]:
# Ans.

# Read the input
import ast, sys

# input_str = sys.stdin.read()
input_str = input()
input_list = ast.literal_eval(input_str)

list_1 = input_list[0]
list_2 = input_list[1]
list_3 = input_list[2]

# Import NumPy
import numpy as np

# Write your code here
mystack = np.vstack((list_1, list_2))
list_3 = np.transpose(list_3)

final_array = np.hstack((mystack, list_3))
print(final_array)

[[[7, 13, 14], [18, 10, 17], [11, 12, 19]], [16, 6, 1], [[5, 8, 4, 3]]]
[[ 7 13 14  5]
 [18 10 17  8]
 [11 12 19  4]
 [16  6  1  3]]
