<h2 style = "color : Brown"> Creating NumPy Arrays </h2 >



 The following ways are commonly used when you know the size of the array beforehand:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [1]:
import numpy as np

##### Tip: Use help to see the syntax when required

In [2]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20

##### Creating a 1 D array of ones

In [3]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

##### Notice that, by default, numpy creates data type = float64



In [4]:
arr.dtype

dtype('float64')

##### Can provide dtype explicitly using dtype


In [5]:
arr = np.ones(5, dtype=int)
arr

array([1, 1, 1, 1, 1])

In [6]:
arr.dtype

dtype('int64')

##### Creating a 5  x 3 array of ones


In [7]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##### Creating array of zeros

In [8]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [9]:
# convert the type into integer.
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [10]:
# Create a list of integers range between 1 to 5.
list(range(1,5))

[1, 2, 3, 4]

In [11]:
np.arange(3)

array([0, 1, 2])

In [12]:
np.arange(3.0)

array([0., 1., 2.])

##### Notice that 3 is included, 35 is not, as in standard python lists

From 3 to 35 with a step of 2

In [13]:
np.arange(3,35,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

##### Array of random numbers 


In [14]:
np.random.randint(2, size=10)

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 1])

In [15]:
np.random.randint(3,5, size=10)

array([3, 3, 4, 4, 3, 4, 3, 4, 4, 4])

##### 2D Array of random numbers 


In [16]:
np.random.random([3,4])

array([[0.0139129 , 0.18540926, 0.99030059, 0.50777984],
       [0.75303324, 0.90627904, 0.60365632, 0.15163075],
       [0.25216026, 0.03055945, 0.04729794, 0.4003096 ]])

###### Sometimes, you know the length of the array, not the step size

Array of length 20 between 1 and 10

In [17]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

<h2 style = "color : Sky blue"> Exercises </h2>



Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
-  `np.random.randint()`: Create a random array of integers within a particular range

In [18]:
np.full([5, 3], 2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [19]:
np.tile([3, 6, -10], 2)

array([  3,   6, -10,   3,   6, -10])

In [20]:
np.eye(4, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [21]:
np.random.random()

0.29036036914940055

In [22]:
np.random.random(4)

array([0.82903575, 0.41643748, 0.92642271, 0.81642935])

In [23]:
np.random.random([4, 2, 3])

array([[[0.05498517, 0.62649779, 0.51196658],
        [0.54498629, 0.41732775, 0.26689139]],

       [[0.9409214 , 0.84089538, 0.20299471],
        [0.27502979, 0.26258129, 0.99155322]],

       [[0.13758364, 0.36517783, 0.86609076],
        [0.75346369, 0.4513942 , 0.70553396]],

       [[0.1510661 , 0.05268386, 0.70875834],
        [0.14300091, 0.88505384, 0.92498725]]])