# Numpy vs Lists 

In [1]:
#Let's define a list in python.
heights = [74, 75, 72, 72, 71]

In [2]:
# Print the heights.
heights

[74, 75, 72, 72, 71]

In [5]:
# Try to multiple heights with a scalar.
try:
  heights * 2.54
except Exception as e:
  print(e)

can't multiply sequence by non-int of type 'float'


In [4]:
import numpy as np

In [6]:
# Deine a NumPy array
np_heights = np.array([74, 75, 72, 72, 71])

In [7]:
np_heights

array([74, 75, 72, 72, 71])

In [8]:
# Print the type of a NumPy array.
type(np_heights)

numpy.ndarray

In [9]:
# Multiple height (NumPy array) with a scalar.
np_heights * 2.54

array([187.96, 190.5 , 182.88, 182.88, 180.34])


#### NumPy comes with its own set of methods and operations

In [10]:
# Let's define two lists and perform '+' operation on that.
list_1 = [1,2,3]
list_2 = [4,5,6]
list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [11]:
# Let's define two NumPy array and perform '+' operation on that.
np1 = np.array([1,2,3])
np2 = np.array([4,5,6])
np1 + np2

array([5, 7, 9])

#### Working with N-D Arrays

In [12]:
np_heights

array([74, 75, 72, 72, 71])

In [13]:
type(np_heights)

numpy.ndarray