# [Operations Over 1-D Arrays](https://learn.upgrad.com/course/4460/segment/33129/196269/603796/3075608)

Extracting Elements from Array
----------

    Description

`From a given array, extract all the elements which are greater than 'm' and less than 'n'. Note: 'm' and 'n' are integer values provided as input.`

    Input format:
    A list of integers on line one
    Integer 'm' on line two
    Integer 'n' on line three

    Output format:
    1-D array containing integers greater than 'm' and smaller than 'n'.

    Sample input:
    [ 1, 5, 9, 12, 15, 7, 12, 9 ] (array)
    6 (m)
    12 (n)

    Sample output:
    [ 9 7 9 ]

    Sample input:
    [ 1, 5, 9, 12, 15, 7, 12, 9 ]
    12
    6

    Sample output:
    [ ]

In [ ]:
#take input here
import ast
input_list=ast.literal_eval(input())
m=int(input())
n=int(input())

#start writing your code from here
import numpy as np 
array_1 = np.array(input_list)
final_array = array_1[(array_1<n) & (array_1>m)]

print(final_array)

In [ ]:
#take input here
import ast 
input_list=ast.literal_eval(input())
m=int(input())
n=int(input())

import numpy as np
array_1 = np.array(input_list)
final_array = array_1[(n > array_1) & (m < array_1)]    # `and` does not work in case of numpy instead use `&`.

print(final_array)

Border Rows and Columns
------------

Description

Extract all the border rows and columns from a 2-D array.

    Format:
    Input: A 2-D Python list
    Output:
      Four NumPy arrays - First column of the input array, first row of the input array, 
      last column of the input array, last row of the input array respectively.

-------------------

    Example:
    
    Input 1:
    [[11 12 13 14]
    [21 22 23 24]
    [31 32 33 34]]

    Output 1:
    [11 21 31]
    [11 12 13 14]
    [14 24 34]
    [31 32 33 34]

In [ ]:
# For a video solution of the code, copy-paste the following link in your browser:
# https://youtu.be/ekELUEdT63E

# Read the input list
import ast,sys
input_str = sys.stdin.read()
input_list = ast.literal_eval(input_str)
import numpy as np

# Convert the input list to a NumPy array
array_2d =np.array(input_list)

# Extract the first column, first row, last column and last row respectively using
# appropriate indexing
col_1 = array_2d[:, 0]
row_1 = array_2d[0, :]
col_last = array_2d[:, -1]
row_last = array_2d[-1, :]

print(col_1)
print(row_1)
print(col_last)
print(row_last)

In [ ]:
# Read the input list
import ast,sys
input_str = sys.stdin.read()
input_list = ast.literal_eval(input_str)

import numpy as np

# Convert the input list to a NumPy array
array_2d = np.array(input_list)

# Extract the first column, first row, last column and last row respectively using
# appropriate indexing
col_first = array_2d[0]
row_first = array_2d[:,0]
col_last = array_2d[:,-1]
row_last = array_2d[-1]

print(row_first)
print(col_first)
print(col_last)
print(row_last)


Array 'arange' Function
-----------

Description

Create an array of first 10 multiples of 5 using the 'arange' function.

----------

Execution Time Limit
15 seconds

In [ ]:
import numpy as np
array_multipleof5 = np.arange(5,51,5)

print(array_multipleof5)

In [ ]:
import numpy as np
array_multipleof5 = np.arange(5,51,5)

print(array_multipleof5)

Create border array
------------

Description

Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.

-------------

Note: Make sure the array is of type int.

    Example:
    Input 1:
    4
    Output 1:
    [[1 1 1 1]
    [1 0 0 1]
    [1 0 0 1]
    [1 1 1 1]]
    Input 2:
    2
    Output 2:
    [[1 1] 
    [1 1]] 

In [ ]:
# Read the variable from STDIN
n = int(input())

import numpy as np

# Create an 'n*n' array of all ones
border_array = np.ones((n, n), dtype = int)

# Fill the array with zeroes from second index (i.e. index 1) to second last index.
# Do this for both row indices and column indices
border_array[1:-1, 1:-1] = 0

# Print the array created
print(border_array)

In [ ]:
# Read the variable from STDIN
n = int(input())

import numpy as np

# Create an 'n*n' array of all ones
np_array = np.ones((n,n), dtype=int)

# Fill the array with zeroes from second index (i.e. index 1) to second last index.
# Do this for both row indices and column indices
np_array[1:-1, 1:-1] = 0

# Print the array created
print(np_array)

# [Coding Questions - I](https://learn.upgrad.com/course/4460/segment/33129/196269/603797/3075618)

Greater than 3
-----------

Description

Given an nxn array, print only the elements that are greater than three as a 1D array.



    Input: nxn array

    Output: 1D array containing elements that are greater than 3



    Sample Input 1: [[9,8,7],[6,5,4],[3,2,1]]

    Sample Output 1: [9 8 7 6 5 4]



    Sample Input 2: [[-1, 2, 0],[1,3,5],[3,2,1]]

    Sample Output 2: [5]

In [ ]:
import numpy as np
import ast

inp_list=ast.literal_eval(input())
arr=np.array(inp_list)

print(arr[arr > 3])

In [ ]:
import numpy as np
import ast
#input has been taken for you
inp_list=ast.literal_eval(input())
arr=np.array(inp_list)

#write your code here
print (arr[arr>3])



Percentile
--------------

Description

Calculate the 60th percentile of the given NumPy array.



    Input: 1D array

    Output: Value of 60th percentile rounded off to two decimal places



    Sample Input 1: [11, 22, 33, 44 ,55 ,66, 77]

    Sample Output 1: 50.6



    Sample Input 2: [-1, 2, 0, 1, 3, 5, 3, 2, 1]

    Sample Output 2: 2.0

In [ ]:
import numpy as np
import ast
arr = np.array(ast.literal_eval(input()))

#Returns the 60th percentile
perc = round(np.percentile(arr, 60),2)
print(perc)

In [ ]:
import numpy as np
import ast

#input has been taken for you
arr = np.array(ast.literal_eval(input()))

# write your code here
print(round(np.percentile(arr,60),1))

Statistics
---------------

Description

Given a positive integer 'n', write a program that computes the mean, the standard deviation and the variance of the numbers starting from 0 to n-1, rounded off to two decimal places.



    Input: First line of input containing mxn array as a nested list and the second line containing an integer 'k' less than 'n'.

    Output: mxn array sorted by column 'n'.



    Sample Input 1: 16

    Sample Output 1: 

    7.5

    4.61

    21.25



    Explanation: 7.5, 4.61, and 21.5 are the mean, standard deviation and variance of the list of numbers from 0 to 15(included).



    Sample Input 2: 23

    Sample Output 2: 

    11.0

    6.63

    44.0

In [ ]:
import numpy as np
n=int(input())
x = np.arange(n)
mean = round(np.mean(x),2)
std = round(np.std(x),2)
var = round(np.var(x),2)
print(mean)
print(std)
print(var)

In [ ]:
import numpy as np
n=int(input())
# write your code here

n_arr=np.arange(n)
print (round((np.mean(n_arr)),2))
print (round((np.std(n_arr)),2))
print (round((np.var(n_arr)),2))

Print Z
-------------

Description

Given a single positive integer 'n' greater than 2, create a NumPy array of size (n x n) will all zeros and ones such that the ones make a shape like 'Z'.

    Examples:
    Input 1:
    3
    Output 1:
    [[1 1 1]
    [0 1 0]
    [1 1 1]]
    Input 2:
    5
    Output 1:
    [[1 1 1 1 1]
    [0 0 0 1 0]
    [0 0 1 0 0]
    [0 1 0 0 0]
    [1 1 1 1 1]]

    Explanation: Notice that the 1s in the array make a shape like 'Z'.

In [ ]:
# Read the input
n = int(input())

# Import the NumPy package
import numpy as np 

# Create an (n x n) array with all zeros
z = np.zeros((n, n), dtype = int)

# Make the first and last rows all 1s
z[0] = np.ones(1, dtype = int)
z[n-1] = np.ones(1, dtype = int)

# Run a loop from the second row (index 1) till the second last row.
for i in range(1, n):
# Fill the 1s in appropriate indices. Notice that for every row index i, the 1 
# will be in the (n-i-1)th row
    z[i][n-i-1] = 1
    
# Print the final value of z    
print(z)

In [ ]:
# Read the input
n = int(input())

# Import the NumPy package
import numpy as np 

# Write your code here

# Create an (n x n) array with all zeros
z = np.zeros((n, n), dtype = int)

# Make the first and last rows all 1s
z[0] = np.ones(1, dtype = int)
z[n-1] = np.ones(1, dtype = int)

# Run a loop from the second row (index 1) till the second last row.
for i in range(1, n):
# Fill the 1s in appropriate indices. Notice that for every row index i, the 1 
# will be in the (n-i-1)th row
    z[i][n-i-1] = 1
    
# Print the final value of z    
print(z)

Sort by Column
------------

Description

Given a 2D NumPy array, sort it by the 1st column. Print the final sorted array as a NumPy array only.

Note: If two values in the 1st column are equal then the column in which the 2nd column value is lesser should come first. If the value in the second column is also the same then go to the third value and so on.

    Example:
    Input 1:
    [[9 3 2]
    [4 0 1]
    [5 8 6]]

    Output 2:
    [[4 0 1]
    [5 8 6]
    [9 3 2]]

    Input 2:
    [[9 3 2]
    [4 0 1]
    [9 8 6]]
    
    Output 2:
    [[4 0 1]
    [9 3 2]
    [9 8 6]]

--------------------

Explanation:
---------------

Example 1: 

Notice that the values in the first column are sorted. Also notice that the whole row should be moved and not just the individual values in the first column. For example, the row with the smallest value, i.e. 4 was moved as a whole. 

Example 2: 

Since this time the first row contains two 9s, the row in which the value in the second column is lesser came first.

In [ ]:
# Reading the input list
import ast,sys
input_str = sys.stdin.read()
input_list = ast.literal_eval(input_str)

# Import the NumPy package
import numpy as np

# Converting the list to a NumPy array
n_array = np.array(input_list)

# Sort the array using the argsort() argument. You can also specify the type of
# sort you need in the argsort() argument but it isn't necessary. Notice the 
# indexing is the main key here. The array is sorted by the row or column that you
# specify in the index
for i in range(len(n_array[0, :])):
    n_array = n_array[n_array[:,-1-i].argsort()]

# Print the final sorted array
print(n_array)

In [ ]:
# Reading the input list
import ast,sys
input_str = sys.stdin.read()
input_list = ast.literal_eval(input_str)

# Import the NumPy package
import numpy as np

# Converting the list to a NumPy array
n_array = np.array(input_list)

# Write your code here
for i in range(len(n_array[0, :])):
    n_array = n_array[n_array[:,-1-i].argsort()]

# Print the final sorted array
print(n_array)

# the end